services:
  sql1:
    container_name: sql1
    hostname: sql1
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Password1234
      PATH: /opt/mssql/bin:/opt/mssql-tools18/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    entrypoint: /usr/scripts/entrypoint.sh
    volumes:
      - ./scripts:/usr/scripts
      - ./log:/usr/log
      - ./backup:/var/opt/mssql/backup              
      - sql-server:/var/opt/mssql                   # Volumen para los datos de la DB

volumes:
  sql-server:
